[project]
name = "rerun-ros"
authors = ["rerun.io <opensource@rerun.io>"]
channels = ["robostack-staging", "conda-forge"]
description = "rerun-ros"
homepage = "https://rerun.io"
license = "MIT OR Apache-2.0"

platforms = ["linux-64"]
readme = "README.md"
repository = "https://github.com/rerun-io/rerun-ros"
version = "0.1.0"

[tasks]
install-cargo-ament-build = "cargo install cargo-ament-build"
build = { cmd = "colcon build", depends-on = ["install-cargo-ament-build"] }

[activation]
env = { ROS_DISTRO = "humble" }
scripts = ["install/setup.bash", "install/local_setup.bash"]

[dependencies]
ros-humble-rcl = ">=5.3.7,<6"
ros-humble-builtin-interfaces = ">=1.2.1,<2"
ros-humble-rcl-interfaces = ">=1.2.1,<2"
ros-humble-rosgraph-msgs = ">=1.2.1,<2"
clangdev = ">=18.1.8,<19"
rust = "1.74.0.*"
ros-humble-rosidl-default-generators = ">=1.2.0,<2"

[build-dependencies]
colcon-common-extensions = ">=0.3.0,<0.4"

[pypi-dependencies]
colcon-cargo = { git = "https://github.com/colcon/colcon-cargo.git" }
colcon-ros-cargo = { git = "https://github.com/colcon/colcon-ros-cargo.git" }
